In [1]:
#1. Create a NumPy array with values from 10 to 50, stepping by 5

import numpy as np

arr = np.arange(10, 51, 5)
print(arr)

[10 15 20 25 30 35 40 45 50]


In [2]:
#2. Turn the array above into a 5×10 matrix

arr = np.arange(10, 510, 10)  # 50 elements (10 to 500)
matrix = arr.reshape(5, 10)
print(matrix)

[[ 10  20  30  40  50  60  70  80  90 100]
 [110 120 130 140 150 160 170 180 190 200]
 [210 220 230 240 250 260 270 280 290 300]
 [310 320 330 340 350 360 370 380 390 400]
 [410 420 430 440 450 460 470 480 490 500]]


In [3]:
#3. Given an array arr = np.array([1, 2, 3, 4, 5]), write code to square each element without using a loop.

arr = np.array([1, 2, 3, 4, 5])
squared = arr ** 2
print(squared)

[ 1  4  9 16 25]


In [4]:
#4. If you have an array a = np.array([[1, 2], [3, 4], [5, 6]]), how do you extract [3, 5]?

a = np.array([[1, 2], [3, 4], [5, 6]])

result = a[[1, 2], 0]
print(result)

[3 5]


In [5]:
#5. Create a DataFrame with two columns: Name and Age, with 3 rows of sample data.

import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 22]
}

df = pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   22


In [6]:
#6. Given the following data

import pandas as pd
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [24, 28, 35, 22]
}

df = pd.DataFrame(data)


# What is the total age of all the students?

data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [24, 28, 35, 22]
}

df = pd.DataFrame(data)
total_age = df['Age'].sum()
print("Total Age:", total_age)

Total Age: 109


In [7]:
#7. How would you extract the records of Peter and Linda from the code above

filtered = df[df['Name'].isin(['Peter', 'Linda'])]
print(filtered)

    Name  Age
2  Peter   35
3  Linda   22


In [9]:
#8. Import this data using pandas
#https://raw.githubusercontent.com/waleolajumoke/data/refs/heads/main/Student.csv


url = "https://raw.githubusercontent.com/waleolajumoke/data/refs/heads/main/Student.csv"
students = pd.read_csv(url)
print(students.head())

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75  


In [10]:
#9. Find out the statistical summary of the data

print(students.describe())

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000


In [11]:
#10. Check out missing values in the data

print(students.isnull().sum())

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64
